# Generated by Django 5.1.4 on 2024-12-26 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="BuildingProductionMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "production_speed",
                    models.FloatField(help_text="production per minute"),
                ),
                (
                    "building",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.building"),
                ),
                (
                    "material",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.material"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BuildingBuildMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField()),
                (
                    "building",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.building"),
                ),
                (
                    "material",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.material"),
                ),
            ],
        ),
    ]
