# Generated by Django 5.1.4 on 2024-12-26 20:33

from django.db import migrations


from django.apps import registry
from ..constants import MaterialNames


def add_wood_material_image(apps: registry.Apps, schema_editor):
    Material = apps.get_model("api", "Material")
    material = Material.objects.get(name=MaterialNames.WOOD, image="")
    material.image = "timber icon.png"
    material.save()


def roll_back_wood_image(apps: registry.Apps, schema_editor):
    Material = apps.get_model("api", "Material")
    material = Material.objects.get(name=MaterialNames.WOOD, image="timber icon.png")
    material.image = ""
    material.save()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_buildingbuildmaterial_building_and_more"),
    ]

    operations = [
        migrations.RunPython(
            code=add_wood_material_image,
            reverse_code=roll_back_wood_image,
        )
    ]
